In [1]:
import pandas as pd
import json

In [2]:
state_json_path = "../Covid-19-Project/state_pop.json"

In [3]:
state_df = pd.read_json(state_json_path)
state_df.head()

        State  Population  State_FIPS   Latitude   Longitude
0     Alabama     4850771           1  32.318231  -86.902298
1      Alaska      738565           2  64.200841 -149.493673
2     Arizona     6809946           4  34.048928 -111.093731
3    Arkansas     2977944           5  35.201050  -91.831833
4  California    38982847           6  36.778261 -119.417932

In [4]:
voter_df = pd.read_excel('../voter-suppression-project/2018_General_Voter_Data.xlsx')
voter_df.head()

,State,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Denominators,Unnamed: 8,VEP Components (Modifications to VAP to Calculate VEP),Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,Estimated or Actual 2018 Total Ballots Counted...,2018 Vote for Highest Office VEP Turnout Rate,Status,Source,Estimated or Actual 2018 Total Ballots Counted,2018 Vote for Highest Office,Voting-Eligible Population (VEP),Voting-Age Population (VAP),% Non-citizen,Prison,Probation,Parole,Total Ineligible Felon,Overseas Eligible,State Abv
1,United States,0.500156,0.493776,NaN,NaN,118581921,117069210,2.3709e+08,2.55802e+08,0.0791282,1416810,2126035,494442,3264172,4793402,NaN
2,Alabama,0.469631,0.468999,Certified,https://www.sos.alabama.gov/sites/default/file...,1721906,1719589,3.66651e+06,3.82054e+06,0.0227848,28680,52177,8562,66982.9,NaN,AL
3,Alaska,0.548186,0.54458,Official,http://www.elections.alaska.gov/results/18GENR/,285009,283134,519913,551451,0.0392326,4317,6621,1812,9902.97,NaN,AK
4,Arizona,0.474193,0.469156,Certified,https://azsos.gov/sites/default/files/2018%201...,2409910,2384308,5.08213e+06,5.67848e+06,0.0893142,37582,77373,7500,89184.6,NaN,AZ

In [5]:
voter_df = voter_df.rename(columns = {"Unnamed: 6":"2018 Vote for Highest Office", "Denominators":"Voting-Eligible_Population(VEP)","Unnamed: 8":"Voting-Age_Population(VAP)"})
voter_df.head()

,State,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,2018 Vote for Highest Office,Voting-Eligible_Population(VEP),Voting-Age_Population(VAP),VEP Components (Modifications to VAP to Calculate VEP),Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,Estimated or Actual 2018 Total Ballots Counted...,2018 Vote for Highest Office VEP Turnout Rate,Status,Source,Estimated or Actual 2018 Total Ballots Counted,2018 Vote for Highest Office,Voting-Eligible Population (VEP),Voting-Age Population (VAP),% Non-citizen,Prison,Probation,Parole,Total Ineligible Felon,Overseas Eligible,State Abv
1,United States,0.500156,0.493776,NaN,NaN,118581921,117069210,2.3709e+08,2.55802e+08,0.0791282,1416810,2126035,494442,3264172,4793402,NaN
2,Alabama,0.469631,0.468999,Certified,https://www.sos.alabama.gov/sites/default/file...,1721906,1719589,3.66651e+06,3.82054e+06,0.0227848,28680,52177,8562,66982.9,NaN,AL
3,Alaska,0.548186,0.54458,Official,http://www.elections.alaska.gov/results/18GENR/,285009,283134,519913,551451,0.0392326,4317,6621,1812,9902.97,NaN,AK
4,Arizona,0.474193,0.469156,Certified,https://azsos.gov/sites/default/files/2018%201...,2409910,2384308,5.08213e+06,5.67848e+06,0.0893142,37582,77373,7500,89184.6,NaN,AZ

In [6]:
voter_df = voter_df[['State','2018 Vote for Highest Office','Voting-Eligible_Population(VEP)','Voting-Age_Population(VAP)' ]]
voter_df.head()

,State,2018 Vote for Highest Office,Voting-Eligible_Population(VEP),Voting-Age_Population(VAP)
0,NaN,2018 Vote for Highest Office,Voting-Eligible Population (VEP),Voting-Age Population (VAP)
1,United States,117069210,2.3709e+08,2.55802e+08
2,Alabama,1719589,3.66651e+06,3.82054e+06
3,Alaska,283134,519913,551451
4,Arizona,2384308,5.08213e+06,5.67848e+06

In [7]:
voter_df = voter_df.drop(0, axis=0)
voter_df.head()

,State,2018 Vote for Highest Office,Voting-Eligible_Population(VEP),Voting-Age_Population(VAP)
1,United States,117069210,2.3709e+08,2.55802e+08
2,Alabama,1719589,3.66651e+06,3.82054e+06
3,Alaska,283134,519913,551451
4,Arizona,2384308,5.08213e+06,5.67848e+06
5,Arkansas,891509,2.17623e+06,2.32103e+06

In [8]:
voter_df

,State,2018 Vote for Highest Office,Voting-Eligible_Population(VEP),Voting-Age_Population(VAP)
1,United States,117069210,2.3709e+08,2.55802e+08
2,Alabama,1719589,3.66651e+06,3.82054e+06
3,Alaska,283134,519913,551451
4,Arizona,2384308,5.08213e+06,5.67848e+06
5,Arkansas,891509,2.17623e+06,2.32103e+06
6,California,12464235,2.57824e+07,3.0659e+07
7,Colorado,2525062,4.21082e+06,4.52329e+06
8,Connecticut,1406803,2.59713e+06,2.83828e+06
9,Delaware,362592,713781,772850
10,District of Columbia,224658,529560,578702
11,Florida,8220561,1.53331e+07,1.73217e+07
12,Georgia,3939328,7.30306e+06,8.14893e+06
13,Hawaii,390843,1.00956e+06,1.11562e+06
14,Idaho,605131,1.26063e+06,1.35032e+06
15,Illinois,4570842,8.99912e+06,9.84865e+06
16,Indiana,2282565,4.96031e+06,5.17682e+06
17,Iowa,1327638,2.30363e+06,2.43111e+06
18,Kansas,1055566,2.07635e+06,2.21561e+06
19,Kentucky,1569798,3.31064e+06,3.46842e+06
20,Louisiana,1460585,3.36767e+06,3.56027e+06
21,Maine,634409,1.07832e+06,1.09765e+06
22,Maryland,2304512,4.31108e+06,4.71559e+06
23,Massachusetts,2707090,5.03737e+06,5.54639e+06
24,Michigan,4250585,7.51996e+06,7.84991e+06
25,Minnesota,2596879,4.0706e+06,4.34704e+06
26,Mississippi,936215,2.19356e+06,2.27803e+06
27,Missouri,2442289,4.58315e+06,4.77383e+06
28,Montana,504384,830480,843058
29,Nebraska,698417,1.37289e+06,1.46122e+06
30,Nevada,972132,2.09984e+06,2.40337e+06
31,New Hampshire,573608,1.07575e+06,1.10732e+06
32,New Jersey,3169310,6.07405e+06,6.94571e+06
33,New Mexico,696459,1.4989e+06,1.62425e+06
34,New York,6104477,1.3621e+07,1.54121e+07
35,North Carolina,3693104,7.66385e+06,8.22269e+06
36,North Dakota,326138,562854,582571
37,Ohio,4429582,8.83219e+06,9.11947e+06
38,Oklahoma,1186385,2.82858e+06,3.0115e+06
39,Oregon,1866997,3.12663e+06,3.36485e+06
40,Pennsylvania,5012555,9.74528e+06,1.01721e+07
41,Rhode Island,376738,802033,855526
42,South Carolina,1707569,3.88184e+06,4.05731e+06
43,South Dakota,339214,642257,669423
44,Tennessee,2243740,5.0733e+06,5.33715e+06
45,Texas,8371655,1.83778e+07,2.17116e+07
46,Utah,1065630,2.14016e+06,2.29193e+06
47,Vermont,274087,499907,510397
48,Virginia,3351373,6.17763e+06,6.68786e+06
49,Washington,3086168,5.3732e+06,5.98139e+06
50,West Virginia,586034,1.40421e+06,1.42996e+06
51,Wisconsin,2673308,4.35453e+06,4.56356e+06
52,Wyoming,203420,428898,445747
53,NaN,NaN,NaN,NaN
54,Notes:,NaN,NaN,NaN
55,Louisiana,NaN,NaN,NaN
56,North Carolina,NaN,NaN,NaN
57,Utah,NaN,NaN,NaN

In [9]:
voter_df = voter_df.drop(53, axis = 0)
voter_df = voter_df.drop(54, axis = 0)
voter_df = voter_df.drop(55, axis = 0)
voter_df = voter_df.drop(56, axis = 0)
voter_df = voter_df.drop(57, axis = 0)
voter_df

,State,2018 Vote for Highest Office,Voting-Eligible_Population(VEP),Voting-Age_Population(VAP)
1,United States,117069210,2.3709e+08,2.55802e+08
2,Alabama,1719589,3.66651e+06,3.82054e+06
3,Alaska,283134,519913,551451
4,Arizona,2384308,5.08213e+06,5.67848e+06
5,Arkansas,891509,2.17623e+06,2.32103e+06
6,California,12464235,2.57824e+07,3.0659e+07
7,Colorado,2525062,4.21082e+06,4.52329e+06
8,Connecticut,1406803,2.59713e+06,2.83828e+06
9,Delaware,362592,713781,772850
10,District of Columbia,224658,529560,578702
11,Florida,8220561,1.53331e+07,1.73217e+07
12,Georgia,3939328,7.30306e+06,8.14893e+06
13,Hawaii,390843,1.00956e+06,1.11562e+06
14,Idaho,605131,1.26063e+06,1.35032e+06
15,Illinois,4570842,8.99912e+06,9.84865e+06
16,Indiana,2282565,4.96031e+06,5.17682e+06
17,Iowa,1327638,2.30363e+06,2.43111e+06
18,Kansas,1055566,2.07635e+06,2.21561e+06
19,Kentucky,1569798,3.31064e+06,3.46842e+06
20,Louisiana,1460585,3.36767e+06,3.56027e+06
21,Maine,634409,1.07832e+06,1.09765e+06
22,Maryland,2304512,4.31108e+06,4.71559e+06
23,Massachusetts,2707090,5.03737e+06,5.54639e+06
24,Michigan,4250585,7.51996e+06,7.84991e+06
25,Minnesota,2596879,4.0706e+06,4.34704e+06
26,Mississippi,936215,2.19356e+06,2.27803e+06
27,Missouri,2442289,4.58315e+06,4.77383e+06
28,Montana,504384,830480,843058
29,Nebraska,698417,1.37289e+06,1.46122e+06
30,Nevada,972132,2.09984e+06,2.40337e+06
31,New Hampshire,573608,1.07575e+06,1.10732e+06
32,New Jersey,3169310,6.07405e+06,6.94571e+06
33,New Mexico,696459,1.4989e+06,1.62425e+06
34,New York,6104477,1.3621e+07,1.54121e+07
35,North Carolina,3693104,7.66385e+06,8.22269e+06
36,North Dakota,326138,562854,582571
37,Ohio,4429582,8.83219e+06,9.11947e+06
38,Oklahoma,1186385,2.82858e+06,3.0115e+06
39,Oregon,1866997,3.12663e+06,3.36485e+06
40,Pennsylvania,5012555,9.74528e+06,1.01721e+07
41,Rhode Island,376738,802033,855526
42,South Carolina,1707569,3.88184e+06,4.05731e+06
43,South Dakota,339214,642257,669423
44,Tennessee,2243740,5.0733e+06,5.33715e+06
45,Texas,8371655,1.83778e+07,2.17116e+07
46,Utah,1065630,2.14016e+06,2.29193e+06
47,Vermont,274087,499907,510397
48,Virginia,3351373,6.17763e+06,6.68786e+06
49,Washington,3086168,5.3732e+06,5.98139e+06
50,West Virginia,586034,1.40421e+06,1.42996e+06
51,Wisconsin,2673308,4.35453e+06,4.56356e+06
52,Wyoming,203420,428898,445747

In [10]:
voter_df.dtypes

State                              object
2018 Vote for Highest Office       object
Voting-Eligible_Population(VEP)    object
Voting-Age_Population(VAP)         object
dtype: object

In [11]:
voter_df['2018 Vote for Highest Office'] = voter_df['2018 Vote for Highest Office'].astype(int)
voter_df.dtypes

State                              object
2018 Vote for Highest Office        int64
Voting-Eligible_Population(VEP)    object
Voting-Age_Population(VAP)         object
dtype: object

In [12]:
voter_df['Voting-Eligible_Population(VEP)'] = voter_df['Voting-Eligible_Population(VEP)'].astype(int)
voter_df.dtypes

State                              object
2018 Vote for Highest Office        int64
Voting-Eligible_Population(VEP)     int64
Voting-Age_Population(VAP)         object
dtype: object

In [13]:
voter_df['Voting-Age_Population(VAP)'] = voter_df['Voting-Age_Population(VAP)'].astype(int)
voter_df.dtypes

State                              object
2018 Vote for Highest Office        int64
Voting-Eligible_Population(VEP)     int64
Voting-Age_Population(VAP)          int64
dtype: object

In [14]:
voter_df.head()

,State,2018 Vote for Highest Office,Voting-Eligible_Population(VEP),Voting-Age_Population(VAP)
1,United States,117069210,237089671,255801551
2,Alabama,1719589,3666511,3820544
3,Alaska,283134,519912,551450
4,Arizona,2384308,5082125,5678478
5,Arkansas,891509,2176225,2321029

In [15]:
voter_df['Percentage_Eligible_Voting'] = voter_df['2018 Vote for Highest Office']/voter_df['Voting-Eligible_Population(VEP)']*100
voter_df.head()

,State,2018 Vote for Highest Office,Voting-Eligible_Population(VEP),Voting-Age_Population(VAP),Percentage_Eligible_Voting
1,United States,117069210,237089671,255801551,49.377609
2,Alabama,1719589,3666511,3820544,46.899873
3,Alaska,283134,519912,551450,54.458062
4,Arizona,2384308,5082125,5678478,46.915572
5,Arkansas,891509,2176225,2321029,40.965847

In [16]:
voter_df['18+_Uneligible'] = voter_df['Voting-Age_Population(VAP)'] - voter_df['Voting-Eligible_Population(VEP)']
voter_df.head()

,State,2018 Vote for Highest Office,Voting-Eligible_Population(VEP),Voting-Age_Population(VAP),Percentage_Eligible_Voting,18+_Uneligible
1,United States,117069210,237089671,255801551,49.377609,18711880
2,Alabama,1719589,3666511,3820544,46.899873,154033
3,Alaska,283134,519912,551450,54.458062,31538
4,Arizona,2384308,5082125,5678478,46.915572,596353
5,Arkansas,891509,2176225,2321029,40.965847,144804

In [17]:
voter_df['18+_Uneligible_Percent'] = voter_df['18+_Uneligible']/voter_df['Voting-Age_Population(VAP)']*100

In [18]:
voter_df.head()

,State,2018 Vote for Highest Office,Voting-Eligible_Population(VEP),Voting-Age_Population(VAP),Percentage_Eligible_Voting,18+_Uneligible,18+_Uneligible_Percent
1,United States,117069210,237089671,255801551,49.377609,18711880,7.314999
2,Alabama,1719589,3666511,3820544,46.899873,154033,4.031703
3,Alaska,283134,519912,551450,54.458062,31538,5.719104
4,Arizona,2384308,5082125,5678478,46.915572,596353,10.501987
5,Arkansas,891509,2176225,2321029,40.965847,144804,6.238785

## Sending info to database

In [19]:
from sqlalchemy import create_engine
import pymysql
import json

from config import remote_db_endpoint, remote_db_port, remote_db_user, remote_db_pwd, remote_db_name

In [20]:
pymysql.install_as_MySQLdb()
engine = create_engine(f"mysql://{remote_db_user}:{remote_db_pwd}@{remote_db_endpoint}/{remote_db_name}")
cxn = engine.connect()

In [22]:
#voter_df.to_sql('2018_voting_data', cxn, if_exists = 'replace', index = False)

## Checking to ensure data has been loaded

In [25]:
aws_check = pd.read_sql("SELECT * FROM 2018_voting_data", cxn)
aws_check

,index,State,2018 Vote for Highest Office,Voting-Eligible_Population(VEP),Voting-Age_Population(VAP),Percentage_Eligible_Voting,18+_Uneligible,18+_Uneligible_Percent
0,1,United States,117069210,237089671,255801551,49.377609,18711880,7.314999
1,2,Alabama,1719589,3666511,3820544,46.899873,154033,4.031703
2,3,Alaska,283134,519912,551450,54.458062,31538,5.719104
3,4,Arizona,2384308,5082125,5678478,46.915572,596353,10.501987
4,5,Arkansas,891509,2176225,2321029,40.965847,144804,6.238785
5,6,California,12464235,25782388,30659000,48.343990,4876612,15.905972
6,7,Colorado,2525062,4210815,4523288,59.966111,312473,6.908094
7,8,Connecticut,1406803,2597133,2838275,54.167538,241142,8.496076
8,9,Delaware,362592,713780,772849,50.798846,59069,7.643020
9,10,District of Columbia,224658,529560,578702,42.423521,49142,8.491763
10,11,Florida,8220561,15333066,17321691,53.613289,1988625,11.480548
11,12,Georgia,3939328,7303056,8148933,53.940816,845877,10.380218
12,13,Hawaii,390843,1009561,1115619,38.714154,106058,9.506651
13,14,Idaho,605131,1260630,1350318,48.002269,89688,6.641991
14,15,Illinois,4570842,8999121,9848646,50.792094,849525,8.625805
15,16,Indiana,2282565,4960307,5176820,46.016607,216513,4.182355
16,17,Iowa,1327638,2303627,2431107,57.632507,127480,5.243702
17,18,Kansas,1055566,2076345,2215607,50.837698,139262,6.285501
18,19,Kentucky,1569798,3310635,3468415,47.416825,157780,4.549052
19,20,Louisiana,1460585,3367669,3560271,43.370800,192602,5.409757
20,21,Maine,634409,1078321,1097649,58.833038,19328,1.760854
21,22,Maryland,2304512,4311082,4715594,53.455536,404512,8.578177
22,23,Massachusetts,2707090,5037365,5546390,53.740199,509025,9.177591
23,24,Michigan,4250585,7519961,7849909,56.524030,329948,4.203208
24,25,Minnesota,2596879,4070604,4347040,63.795913,276436,6.359178
25,26,Mississippi,936215,2193563,2278027,42.680105,84464,3.707770
26,27,Missouri,2442289,4583151,4773831,53.288425,190680,3.994276
27,28,Montana,504384,830479,843058,60.734106,12579,1.492068
28,29,Nebraska,698417,1372893,1461219,50.871918,88326,6.044679
29,30,Nevada,972132,2099841,2403374,46.295505,303533,12.629453
30,31,New Hampshire,573608,1075752,1107322,53.321583,31570,2.851023
31,32,New Jersey,3169310,6074050,6945710,52.177871,871660,12.549617
32,33,New Mexico,696459,1498899,1624252,46.464705,125353,7.717583
33,34,New York,6104477,13620989,15412110,44.816694,1791121,11.621517
34,35,North Carolina,3693104,7663854,8222687,48.188601,558833,6.796233
35,36,North Dakota,326138,562853,582570,57.943726,19717,3.384486
36,37,Ohio,4429582,8832186,9119467,50.152725,287281,3.150195
37,38,Oklahoma,1186385,2828576,3011497,41.942836,182921,6.074089
38,39,Oregon,1866997,3126629,3364846,59.712777,238217,7.079581
39,40,Pennsylvania,5012555,9745275,10172074,51.435747,426799,4.195791
40,41,Rhode Island,376738,802033,855526,46.972880,53493,6.252645
41,42,South Carolina,1707569,3881839,4057306,43.988661,175467,4.324717
42,43,South Dakota,339214,642257,669422,52.815929,27165,4.057978
43,44,Tennessee,2243740,5073295,5337147,44.226484,263852,4.943690
44,45,Texas,8371655,18377841,21711618,45.552984,3333777,15.354807
45,46,Utah,1065630,2140158,2291926,49.792118,151768,6.621854
46,47,Vermont,274087,499906,510397,54.827708,10491,2.055459
47,48,Virginia,3351373,6177625,6687863,54.250185,510238,7.629313
48,49,Washington,3086168,5373201,5981385,57.436303,608184,10.167946
49,50,West Virginia,586034,1404205,1429959,41.734220,25754,1.801031
50,51,Wisconsin,2673308,4354526,4563564,61.391481,209038,4.580587
51,52,Wyoming,203420,428898,445747,47.428526,16849,3.779947